// Code generated by protoc-gen-go.
// source: backend.proto
// DO NOT EDIT!

/*
Package mwitkow_grpcproxy_backendpool is a generated protocol buffer package.

It is generated from these files:
	backend.proto
	config.proto

It has these top-level messages:
	Backend
	Interceptor
	Security
	SrvResolver
	KubeResolver
	Config
	TlsServerConfig
*/
package mwitkow_grpcproxy_backendpool

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Balancer chooses which gRPC balancing policy to use.
type Balancer int32

const (
	// ROUND_ROBIN is the simpliest and default load balancing policy
	Balancer_ROUND_ROBIN Balancer = 0
)

var Balancer_name = map[int32]string{
	0: "ROUND_ROBIN",
}
var Balancer_value = map[string]int32{
	"ROUND_ROBIN": 0,
}

func (x Balancer) String() string {
	return proto.EnumName(Balancer_name, int32(x))
}
func (Balancer) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// / Backend is a gRPC ClientConn pool maintained to a single serivce.
type Backend struct {
	// / name is the string identifying the bakcend in all other conifgs.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// / balancer decides which balancing policy to use.
	Balancer Balancer `protobuf:"varint,2,opt,name=balancer,enum=mwitkow.grpcproxy.backendpool.Balancer" json:"balancer,omitempty"`
	// / disable_conntracking turns off the /debug/events tracing and Prometheus monitoring of the pool sie for this backend.
	DisableConntracking bool `protobuf:"varint,3,opt,name=disable_conntracking,json=disableConntracking" json:"disable_conntracking,omitempty"`
	// / security controls the TLS connection details for the backend. If not present, Insecure (plain text) mode is used.
	Security *Security `protobuf:"bytes,4,opt,name=security" json:"security,omitempty"`
	// / interceptors controls what interceptors will be enabled for this backend.
	Interceptors []*Interceptor `protobuf:"bytes,5,rep,name=interceptors" json:"interceptors,omitempty"`
	// Types that are valid to be assigned to Resolver:
	//	*Backend_Srv
	//	*Backend_K8S
	Resolver isBackend_Resolver `protobuf_oneof:"resolver"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isBackend_Resolver interface {
	isBackend_Resolver()
}

type Backend_Srv struct {
	Srv *SrvResolver `protobuf:"bytes,10,opt,name=srv,oneof"`
}
type Backend_K8S struct {
	K8S *KubeResolver `protobuf:"bytes,11,opt,name=k8s,oneof"`
}

func (*Backend_Srv) isBackend_Resolver() {}
func (*Backend_K8S) isBackend_Resolver() {}

func (m *Backend) GetResolver() isBackend_Resolver {
	if m != nil {
		return m.Resolver
	}
	return nil
}

func (m *Backend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Backend) GetBalancer() Balancer {
	if m != nil {
		return m.Balancer
	}
	return Balancer_ROUND_ROBIN
}

func (m *Backend) GetDisableConntracking() bool {
	if m != nil {
		return m.DisableConntracking
	}
	return false
}

func (m *Backend) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *Backend) GetInterceptors() []*Interceptor {
	if m != nil {
		return m.Interceptors
	}
	return nil
}

func (m *Backend) GetSrv() *SrvResolver {
	if x, ok := m.GetResolver().(*Backend_Srv); ok {
		return x.Srv
	}
	return nil
}

func (m *Backend) GetK8S() *KubeResolver {
	if x, ok := m.GetResolver().(*Backend_K8S); ok {
		return x.K8S
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Backend) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Backend_OneofMarshaler, _Backend_OneofUnmarshaler, _Backend_OneofSizer, []interface{}{
		(*Backend_Srv)(nil),
		(*Backend_K8S)(nil),
	}
}

func _Backend_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Srv); err != nil {
			return err
		}
	case *Backend_K8S:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.K8S); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Backend.Resolver has unexpected type %T", x)
	}
	return nil
}

func _Backend_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Backend)
	switch tag {
	case 10: // resolver.srv
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SrvResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_Srv{msg}
		return true, err
	case 11: // resolver.k8s
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KubeResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_K8S{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Backend_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		s := proto.Size(x.Srv)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Backend_K8S:
		s := proto.Size(x.K8S)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Interceptor struct {
	// Types that are valid to be assigned to Interceptor:
	//	*Interceptor_Prometheus
	Interceptor isInterceptor_Interceptor `protobuf_oneof:"interceptor"`
}

func (m *Interceptor) Reset()                    { *m = Interceptor{} }
func (m *Interceptor) String() string            { return proto.CompactTextString(m) }
func (*Interceptor) ProtoMessage()               {}
func (*Interceptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isInterceptor_Interceptor interface {
	isInterceptor_Interceptor()
}

type Interceptor_Prometheus struct {
	Prometheus bool `protobuf:"varint,1,opt,name=prometheus,oneof"`
}

func (*Interceptor_Prometheus) isInterceptor_Interceptor() {}

func (m *Interceptor) GetInterceptor() isInterceptor_Interceptor {
	if m != nil {
		return m.Interceptor
	}
	return nil
}

func (m *Interceptor) GetPrometheus() bool {
	if x, ok := m.GetInterceptor().(*Interceptor_Prometheus); ok {
		return x.Prometheus
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Interceptor) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Interceptor_OneofMarshaler, _Interceptor_OneofUnmarshaler, _Interceptor_OneofSizer, []interface{}{
		(*Interceptor_Prometheus)(nil),
	}
}

func _Interceptor_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Interceptor)
	// interceptor
	switch x := m.Interceptor.(type) {
	case *Interceptor_Prometheus:
		t := uint64(0)
		if x.Prometheus {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Interceptor.Interceptor has unexpected type %T", x)
	}
	return nil
}

func _Interceptor_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Interceptor)
	switch tag {
	case 1: // interceptor.prometheus
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Interceptor = &Interceptor_Prometheus{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Interceptor_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Interceptor)
	// interceptor
	switch x := m.Interceptor.(type) {
	case *Interceptor_Prometheus:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// / Security settings for a backend.
type Security struct {
	// / insecure_skip_verify skips the server certificate verification completely.
	// / No TLS config (for client or server) will be used. This should *not* be used in production software.
	InsecureSkipVerify bool `protobuf:"varint,1,opt,name=insecure_skip_verify,json=insecureSkipVerify" json:"insecure_skip_verify,omitempty"`
	// / config_name indicates the TlsServerConfig to be used for this connection.
	ConfigName string `protobuf:"bytes,2,opt,name=config_name,json=configName" json:"config_name,omitempty"`
}

func (m *Security) Reset()                    { *m = Security{} }
func (m *Security) String() string            { return proto.CompactTextString(m) }
func (*Security) ProtoMessage()               {}
func (*Security) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Security) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Security) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

// / SrvBackend describes a gRPC backend that is resolved and load balanced using SRV.
type SrvResolver struct {
	// / dns_name specifies the address to look up using DNS SRV. Needs to be a FQDN.
	// / E.g. "_grpc._tcp.someservice.somenamespace.svc.cluster.local"
	DnsName string `protobuf:"bytes,2,opt,name=dns_name,json=dnsName" json:"dns_name,omitempty"`
}

func (m *SrvResolver) Reset()                    { *m = SrvResolver{} }
func (m *SrvResolver) String() string            { return proto.CompactTextString(m) }
func (*SrvResolver) ProtoMessage()               {}
func (*SrvResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SrvResolver) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

// / KubeResolver uses the Kubernetes Endpoints API to identify the service.
// / It requires the job to run inside a K8S pod and uses the pod's credentails to fetch the service information.
type KubeResolver struct {
	// / namespace is the k8s namespace to use.
	// / If unset, it deafults to 'deafult'.
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	// / service_name is the k8s service name to use.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	// / port_name is the name of the port to bind in the service.
	PortName string `protobuf:"bytes,3,opt,name=port_name,json=portName" json:"port_name,omitempty"`
}

func (m *KubeResolver) Reset()                    { *m = KubeResolver{} }
func (m *KubeResolver) String() string            { return proto.CompactTextString(m) }
func (*KubeResolver) ProtoMessage()               {}
func (*KubeResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KubeResolver) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *KubeResolver) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *KubeResolver) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func init() {
	proto.RegisterType((*Backend)(nil), "mwitkow.grpcproxy.backendpool.Backend")
	proto.RegisterType((*Interceptor)(nil), "mwitkow.grpcproxy.backendpool.Interceptor")
	proto.RegisterType((*Security)(nil), "mwitkow.grpcproxy.backendpool.Security")
	proto.RegisterType((*SrvResolver)(nil), "mwitkow.grpcproxy.backendpool.SrvResolver")
	proto.RegisterType((*KubeResolver)(nil), "mwitkow.grpcproxy.backendpool.KubeResolver")
	proto.RegisterEnum("mwitkow.grpcproxy.backendpool.Balancer", Balancer_name, Balancer_value)
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0x96, 0xc1, 0xd2, 0xe7, 0x0e, 0x90, 0xd9, 0x21, 0x68, 0x20, 0x42, 0x2f, 0x44, 0x43,
	0x8a, 0x60, 0x5c, 0x76, 0x1a, 0x52, 0xc6, 0x61, 0x13, 0x52, 0x27, 0xb9, 0x82, 0x1b, 0x8a, 0x12,
	0xf7, 0xad, 0x58, 0x49, 0x6d, 0xcb, 0x4e, 0x33, 0xfa, 0xc9, 0xf8, 0x7a, 0x28, 0x6e, 0xba, 0x99,
	0x0b, 0xbd, 0x25, 0xbf, 0x7f, 0xf6, 0x7b, 0xf9, 0x05, 0x8e, 0xab, 0x92, 0xd7, 0x28, 0x17, 0x99,
	0x36, 0xaa, 0x55, 0xf4, 0xcd, 0xea, 0x5e, 0xb4, 0xb5, 0xba, 0xcf, 0x96, 0x46, 0x73, 0x6d, 0xd4,
	0xef, 0x4d, 0x36, 0x08, 0xb4, 0x52, 0xcd, 0xf4, 0x4f, 0x08, 0x47, 0xf9, 0xf6, 0x9d, 0x52, 0x38,
	0x94, 0xe5, 0x0a, 0xe3, 0x20, 0x09, 0xd2, 0x31, 0x73, 0xcf, 0xf4, 0x0a, 0xa2, 0xaa, 0x6c, 0x4a,
	0xc9, 0xd1, 0xc4, 0x07, 0x49, 0x90, 0x3e, 0x3b, 0x7f, 0x9f, 0xfd, 0x37, 0x31, 0xcb, 0x07, 0x39,
	0x7b, 0x30, 0xd2, 0x4f, 0x70, 0xb2, 0x10, 0xb6, 0xac, 0x1a, 0x2c, 0xb8, 0x92, 0xb2, 0x35, 0x25,
	0xaf, 0x85, 0x5c, 0xc6, 0x61, 0x12, 0xa4, 0x11, 0x7b, 0x39, 0x70, 0x57, 0x1e, 0xd5, 0x9f, 0x6b,
	0x91, 0xaf, 0x8d, 0x68, 0x37, 0xf1, 0x61, 0x12, 0xa4, 0x64, 0xef, 0xb9, 0xf3, 0x41, 0xce, 0x1e,
	0x8c, 0x74, 0x06, 0x13, 0x21, 0x5b, 0x34, 0x1c, 0x75, 0xab, 0x8c, 0x8d, 0x9f, 0x24, 0x61, 0x4a,
	0xce, 0xcf, 0xf6, 0x04, 0xdd, 0x3c, 0x5a, 0xd8, 0x3f, 0x7e, 0x7a, 0x09, 0xa1, 0x35, 0x5d, 0x0c,
	0xee, 0x3e, 0xfb, 0x62, 0xe6, 0xa6, 0x63, 0x68, 0x55, 0xd3, 0xa1, 0xb9, 0x1e, 0xb1, 0xde, 0x48,
	0xbf, 0x40, 0x58, 0x5f, 0xd8, 0x98, 0x38, 0xff, 0x87, 0x3d, 0xfe, 0x6f, 0xeb, 0x0a, 0xfd, 0x80,
	0xfa, 0xc2, 0xe6, 0x00, 0x91, 0x19, 0xa0, 0xe9, 0x25, 0x10, 0xef, 0xa6, 0x34, 0x01, 0xd0, 0x46,
	0xad, 0xb0, 0xfd, 0x85, 0x6b, 0xeb, 0x3e, 0x61, 0x74, 0x3d, 0x62, 0x1e, 0x96, 0x1f, 0x03, 0xf1,
	0xa6, 0x99, 0xfe, 0x84, 0x68, 0xb7, 0x32, 0xfa, 0x11, 0x4e, 0x84, 0x74, 0x6b, 0xc3, 0xc2, 0xd6,
	0x42, 0x17, 0x1d, 0x1a, 0x71, 0xb7, 0xd9, 0xc6, 0x30, 0xba, 0xe3, 0xe6, 0xb5, 0xd0, 0x3f, 0x1c,
	0x43, 0xdf, 0x02, 0xe1, 0x4a, 0xde, 0x89, 0x65, 0xe1, 0x2a, 0x73, 0xe0, 0x2a, 0x03, 0x5b, 0x68,
	0x56, 0xae, 0x70, 0x9a, 0x02, 0xf1, 0x36, 0x40, 0x5f, 0x41, 0xb4, 0x90, 0xd6, 0x17, 0x1f, 0x2d,
	0xa4, 0x75, 0xca, 0x06, 0x26, 0xfe, 0xac, 0xf4, 0x35, 0x8c, 0x7b, 0x99, 0xd5, 0x25, 0xdf, 0x75,
	0xf1, 0x11, 0xa0, 0xef, 0x60, 0x62, 0xd1, 0x74, 0x82, 0xa3, 0x1f, 0x46, 0x06, 0xac, 0x0f, 0xa4,
	0xa7, 0x30, 0xd6, 0xca, 0xb4, 0x5b, 0x3e, 0x74, 0x7c, 0xd4, 0x03, 0x3d, 0x79, 0x76, 0x0a, 0xd1,
	0xae, 0xa1, 0xf4, 0x39, 0x10, 0x76, 0xfb, 0x7d, 0xf6, 0xb5, 0x60, 0xb7, 0xf9, 0xcd, 0xec, 0xc5,
	0xa8, 0x7a, 0xea, 0xfe, 0x99, 0xcf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x74, 0x93, 0x4c, 0xd7,
	0x44, 0x03, 0x00, 0x00,
}
