// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package mwitkow_grpcproxy_director is a generated protocol buffer package.

It is generated from these files:
	config.proto
	route.proto

It has these top-level messages:
	Config
	Route
*/
package mwitkow_grpcproxy_director

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Config is the top level configuration message the director.
type Config struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "mwitkow.grpcproxy.director.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xca, 0x2d, 0xcf, 0x2c, 0xc9, 0xce,
	0x2f, 0xd7, 0x4b, 0x2f, 0x2a, 0x48, 0x2e, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x4b, 0xc9, 0x2c, 0x4a,
	0x4d, 0x2e, 0xc9, 0x2f, 0x92, 0xe2, 0x2e, 0xca, 0x2f, 0x2d, 0x49, 0x85, 0x28, 0x54, 0x72, 0xe6,
	0x62, 0x73, 0x06, 0x6b, 0x14, 0xb2, 0xe4, 0x62, 0x03, 0x4b, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b,
	0x70, 0x1b, 0x29, 0xea, 0xe1, 0x36, 0x43, 0x2f, 0x08, 0xa4, 0x32, 0x08, 0xaa, 0x21, 0x89, 0x0d,
	0x6c, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x4d, 0x89, 0x99, 0x84, 0x00, 0x00, 0x00,
}
