// Code generated by protoc-gen-go.
// source: serverstatus.proto
// DO NOT EDIT!

/*
Package base is a generated protocol buffer package.

It is generated from these files:
	serverstatus.proto

It has these top-level messages:
	HealthCheckResponse
	FlagzState
	VersionResponse
*/
package base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckResponse struct {
	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk" json:"is_ok,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HealthCheckResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type FlagzState struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Help         string `protobuf:"bytes,2,opt,name=help" json:"help,omitempty"`
	CurrentValue string `protobuf:"bytes,3,opt,name=current_value,json=currentValue" json:"current_value,omitempty"`
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
}

func (m *FlagzState) Reset()                    { *m = FlagzState{} }
func (m *FlagzState) String() string            { return proto.CompactTextString(m) }
func (*FlagzState) ProtoMessage()               {}
func (*FlagzState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FlagzState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlagzState) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *FlagzState) GetCurrentValue() string {
	if m != nil {
		return m.CurrentValue
	}
	return ""
}

func (m *FlagzState) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

type VersionResponse struct {
	Hash       string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Branchname string `protobuf:"bytes,2,opt,name=branchname" json:"branchname,omitempty"`
	Date       string `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Go         string `protobuf:"bytes,4,opt,name=go" json:"go,omitempty"`
	Epoch      string `protobuf:"bytes,5,opt,name=epoch" json:"epoch,omitempty"`
	Tag        string `protobuf:"bytes,6,opt,name=tag" json:"tag,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VersionResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *VersionResponse) GetBranchname() string {
	if m != nil {
		return m.Branchname
	}
	return ""
}

func (m *VersionResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *VersionResponse) GetGo() string {
	if m != nil {
		return m.Go
	}
	return ""
}

func (m *VersionResponse) GetEpoch() string {
	if m != nil {
		return m.Epoch
	}
	return ""
}

func (m *VersionResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "base.HealthCheckResponse")
	proto.RegisterType((*FlagzState)(nil), "base.FlagzState")
	proto.RegisterType((*VersionResponse)(nil), "base.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServerStatus service

type ServerStatusClient interface {
	// Serves as a simple Healthcheck of the service.
	HealthCheck(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Lists all Flagz states for this server.
	FlagzList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (ServerStatus_FlagzListClient, error)
	// Version returns the git hash and other used when building this server.
	Version(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type serverStatusClient struct {
	cc *grpc.ClientConn
}

func NewServerStatusClient(cc *grpc.ClientConn) ServerStatusClient {
	return &serverStatusClient{cc}
}

func (c *serverStatusClient) HealthCheck(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/base.ServerStatus/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverStatusClient) FlagzList(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (ServerStatus_FlagzListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServerStatus_serviceDesc.Streams[0], c.cc, "/base.ServerStatus/FlagzList", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStatusFlagzListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerStatus_FlagzListClient interface {
	Recv() (*FlagzState, error)
	grpc.ClientStream
}

type serverStatusFlagzListClient struct {
	grpc.ClientStream
}

func (x *serverStatusFlagzListClient) Recv() (*FlagzState, error) {
	m := new(FlagzState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverStatusClient) Version(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/base.ServerStatus/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServerStatus service

type ServerStatusServer interface {
	// Serves as a simple Healthcheck of the service.
	HealthCheck(context.Context, *google_protobuf.Empty) (*HealthCheckResponse, error)
	// Lists all Flagz states for this server.
	FlagzList(*google_protobuf.Empty, ServerStatus_FlagzListServer) error
	// Version returns the git hash and other used when building this server.
	Version(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterServerStatusServer(s *grpc.Server, srv ServerStatusServer) {
	s.RegisterService(&_ServerStatus_serviceDesc, srv)
}

func _ServerStatus_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatusServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.ServerStatus/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatusServer).HealthCheck(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerStatus_FlagzList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerStatusServer).FlagzList(m, &serverStatusFlagzListServer{stream})
}

type ServerStatus_FlagzListServer interface {
	Send(*FlagzState) error
	grpc.ServerStream
}

type serverStatusFlagzListServer struct {
	grpc.ServerStream
}

func (x *serverStatusFlagzListServer) Send(m *FlagzState) error {
	return x.ServerStream.SendMsg(m)
}

func _ServerStatus_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatusServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.ServerStatus/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatusServer).Version(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.ServerStatus",
	HandlerType: (*ServerStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ServerStatus_HealthCheck_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _ServerStatus_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FlagzList",
			Handler:       _ServerStatus_FlagzList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "serverstatus.proto",
}

func init() { proto.RegisterFile("serverstatus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x9b, 0x36, 0xed, 0xbd, 0x3d, 0xb7, 0x57, 0xcb, 0xa9, 0x4a, 0xac, 0x20, 0x12, 0x37,
	0xe2, 0x22, 0x15, 0x5d, 0xe9, 0x52, 0x51, 0x5c, 0x08, 0x42, 0x0b, 0xdd, 0x96, 0x49, 0x7a, 0x9a,
	0x84, 0xa6, 0x99, 0x30, 0x33, 0x29, 0xe8, 0xc2, 0x77, 0xf0, 0xb1, 0x7c, 0x2b, 0x99, 0x99, 0x44,
	0x8b, 0xd8, 0xdd, 0xc9, 0x97, 0xff, 0xcc, 0xfc, 0x7c, 0x03, 0x28, 0x49, 0xac, 0x49, 0x48, 0xc5,
	0x54, 0x29, 0x83, 0x42, 0x70, 0xc5, 0xd1, 0x0d, 0x99, 0xa4, 0xe1, 0x51, 0xcc, 0x79, 0x9c, 0xd1,
	0xc8, 0xb0, 0xb0, 0x5c, 0x8c, 0x68, 0x55, 0xa8, 0x17, 0x1b, 0xf1, 0xcf, 0x61, 0xf0, 0x48, 0x2c,
	0x53, 0xc9, 0x5d, 0x42, 0xd1, 0x72, 0x4c, 0xb2, 0xe0, 0xb9, 0x24, 0x1c, 0x40, 0x3b, 0x95, 0x33,
	0xbe, 0xf4, 0x9c, 0x13, 0xe7, 0xec, 0xef, 0xd8, 0x4d, 0xe5, 0xf3, 0xd2, 0x7f, 0x03, 0x78, 0xc8,
	0x58, 0xfc, 0x3a, 0x51, 0x4c, 0x11, 0x22, 0xb8, 0x39, 0x5b, 0x91, 0x49, 0x74, 0xc7, 0x66, 0xd6,
	0x2c, 0xa1, 0xac, 0xf0, 0x9a, 0x96, 0xe9, 0x19, 0x4f, 0xe1, 0x7f, 0x54, 0x0a, 0x41, 0xb9, 0x9a,
	0xad, 0x59, 0x56, 0x92, 0xd7, 0x32, 0x3f, 0x7b, 0x15, 0x9c, 0x6a, 0xa6, 0x43, 0x73, 0x5a, 0xb0,
	0x32, 0xab, 0x43, 0xae, 0x0d, 0x55, 0xd0, 0x84, 0xfc, 0x77, 0x07, 0x76, 0xa7, 0x24, 0x64, 0xca,
	0xf3, 0xaf, 0xa2, 0xfa, 0x46, 0x26, 0x93, 0xba, 0x85, 0x9e, 0xf1, 0x18, 0x20, 0x14, 0x2c, 0x8f,
	0x12, 0xd3, 0xcf, 0x76, 0xd9, 0x20, 0x7a, 0x67, 0xce, 0x54, 0x5d, 0xc4, 0xcc, 0xb8, 0x03, 0xcd,
	0x98, 0x57, 0xb7, 0x36, 0x63, 0x8e, 0x7b, 0xd0, 0xa6, 0x82, 0x47, 0x89, 0xd7, 0x36, 0xc8, 0x7e,
	0x60, 0x1f, 0x5a, 0x8a, 0xc5, 0x5e, 0xc7, 0x30, 0x3d, 0x5e, 0x7e, 0x38, 0xd0, 0x9b, 0x18, 0xf3,
	0x13, 0x63, 0x1e, 0x6f, 0xe1, 0xdf, 0x86, 0x50, 0x3c, 0x08, 0xac, 0xfd, 0xa0, 0xb6, 0x1f, 0xdc,
	0x6b, 0xfb, 0xc3, 0xc3, 0x40, 0xbf, 0x4d, 0xf0, 0x8b, 0x7b, 0xbf, 0x81, 0xd7, 0xd0, 0x35, 0xa2,
	0x9f, 0x52, 0xa9, 0xb6, 0x9e, 0xd0, 0xb7, 0x27, 0x7c, 0xbf, 0x88, 0xdf, 0xb8, 0x70, 0xf0, 0x06,
	0xfe, 0x54, 0x8a, 0xb6, 0x2e, 0xee, 0xdb, 0xc5, 0x1f, 0x26, 0xfd, 0x46, 0xd8, 0x31, 0xc1, 0xab,
	0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x67, 0xfb, 0x39, 0x4b, 0x02, 0x00, 0x00,
}
